In [1]:
#20BCAB59
#1.Define and print a 6 dimensional vector

import numpy as np
X=np.array([[10,11,12,13,14,15]])
print(X)

[[10 11 12 13 14 15]]


In [2]:
#2.Print the transpose of the above vector
print(X.T)

[[10]
 [11]
 [12]
 [13]
 [14]
 [15]]


In [3]:
#3.Define two non square matrices such that they can be multiplied.
A=np.array([[1,2],[3,4],[5,6]])
B=np.array([[1,2,3],[4,5,6]])

In [4]:
#4.print the shape of the above matrices
print(np.shape(A),np.shape(B))

(3, 2) (2, 3)


In [7]:
#5.Print the product of above two matrices(do so without using the inbuilt functions).
#3X2 matrix
X=[[1,2],
   [3,4],
   [5,6]]

#2X3 matrix
Y=[[1,2,3],
  [4,5,6]]


In [8]:
#result is 3X3
result=[[0,0,0],
        [0,0,0],
        [0,0,0]]

In [9]:
#iterating through rows of X
for i in range(len(X)):
    #iterating through columns of Y
    for j in range(len(Y[0])):
        #iterating through rows of Y
        for k in range(len(Y)):
            result[i][j]=result[i][j]+X[i][k]*Y[k][j]
for r in result:
 print(r)  


[9, 12, 15]
[19, 26, 33]
[29, 40, 51]


In [10]:
#6. Define two non square matrices of same order and print their sum.
X=np.array([[1,2,3],[4,5,6]])
Y=np.array([[4,3,2],[7,8,2]])
print(X+Y)


[[ 5  5  5]
 [11 13  8]]


In [11]:
#7.Define a square matrix A
A=np.array([[3,4,8],[5,6,7],[7,6,5]])

In [12]:
#8.Print the transpose of A
print(A.T)

[[3 5 7]
 [4 6 6]
 [8 7 5]]


In [13]:
#9.Print the identity matrix of the above order I.
I=np.array([[1,0,0],[0,1,0],[0,0,1]])
print(I)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [14]:
# 10.Verify A.I=I.A for matrix multiplication.
A=np.array([[3,4,8],[5,6,7],[7,6,5]])
I=np.array([[1,0,0],[0,1,0],[0,0,1]])
X=A@I
print("A.I=",X)
Y=I@A
print("I.A=",Y)
print("Therefore verified, A.I=I.A")

A.I= [[3 4 8]
 [5 6 7]
 [7 6 5]]
I.A= [[3 4 8]
 [5 6 7]
 [7 6 5]]
Therefore verified, A.I=I.A


In [15]:
#11. Define another square matrix of the same order as A
B=np.array([[2,1,9],[2,4,8],[1,6,8]])

In [16]:
#12.Print the product of the matrices as matrix multiplication
print(A@B)

[[ 22  67 123]
 [ 29  71 149]
 [ 31  61 151]]


In [17]:
#13.Print the product of the matrices by element wise multiplication
print(np.multiply(A,B))

[[ 6  4 72]
 [10 24 56]
 [ 7 36 40]]


In [18]:
#14.Calculate and print the inverse of A.(Use linalg)
#Check if determinant is 0
#Use if else statement to calculate inverse only when determinant is non 0.
z=np.linalg.det(A)
print("The determinant is=",z)
if z!=0:
    print("The inverse of A is=",np.linalg.inv(A))
else:
    print("Inverse does not exist")

The determinant is= -36.00000000000003
The inverse of A is= [[ 0.33333333 -0.77777778  0.55555556]
 [-0.66666667  1.13888889 -0.52777778]
 [ 0.33333333 -0.27777778  0.05555556]]
